name: silent-cli-execution

on: [push, workflow_dispatch]

jobs:
  job1:
    runs-on: self-hosted
    steps:
    - name: exec-test1to6
      id: test1to6
      run: C:\Users\elgin.ramos\actions-runner\_work\RD11\RD11\01_06\test01_06.bat
      shell: cmd
  job2:
    runs-on: self-hosted
    steps:
    - name: exec-test07to12
      id: test07to12
      run: C:\Users\elgin.ramos\actions-runner\_work\RD11\RD11\07_12\test07_12.bat
      shell: cmd
  job3:
    runs-on: self-hosted
    steps:
    - name: exec-test13to18
      id: test1to6
      run: C:\Users\elgin.ramos\actions-runner\_work\RD11\RD11\13_18\test13_18.bat
      shell: cmd
  job4:
    runs-on: self-hosted
    steps:
    - name: exec-test19to24
      id: test19to24
      run: C:\Users\elgin.ramos\actions-runner\_work\RD11\RD11\19_24\test19_24.bat
      shell: cmd
  job5:
    runs-on: self-hosted
    steps:
    - name: exec-test25to30
      id: test25to30
      run: C:\Users\elgin.ramos\actions-runner\_work\RD11\RD11\25_30\test25_30.bat
      shell: cmd


