name: clrlog25to30

on: [workflow_dispatch]

jobs:
  job1:
    runs-on: self-hosted
    steps:
    - name: exec-test25to30
      id: test25to30
      run: |
        cd C:\Users\elgin.ramos\actions-runner\_work\RD11\RD11\25_30
        C:\Users\elgin.ramos\actions-runner\_work\RD11\RD11\25_30\clrlog.bat
      shell: cmd
