name: SCLI01to06

on: [workflow_dispatch]

jobs:
  job1:
    runs-on: self-hosted
    steps:
    - name: exec-test01to06
      id: test01to06
      run: |
        cd C:\Users\elgin.ramos\actions-runner\_work\RD11\RD11\01_06
        C:\Users\elgin.ramos\actions-runner\_work\RD11\RD11\01_06\testrun.bat
      shell: cmd
